// AUTO-GENERATED by build-config.js — do not edit by hand.
// Regenerate with: node build-config.js
// This file is safe to ship (anon key is a public, RLS-protected key),
// but keep your real ".env" out of source control.
export const CONFIG = Object.freeze({
  APP_NAME: "Vyrona",
  SUPABASE_URL: "https://YOUR-PROJECT-REF.supabase.co",
  SUPABASE_ANON_KEY: "your-anon-public-key-here",
  SUPABASE_CONFIGURED: false,
});
