#!/usr/bin/env node
/**
 * Vyrona config builder.
 *
 * Reads ".env" (falling back to ".env.example" if missing, so the app still
 * boots in offline/guest mode) and writes "js/config.js" — a small ES module
 * that the rest of the app imports. This keeps Supabase credentials out of
 * index.html / the login screen and out of source control (.env is
 * git-ignored).
 *
 * Usage:
 *   node build-config.js
 *
 * No dependencies required — plain Node.js only.
 */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const ENV_PATH = path.join(ROOT, ".env");
const ENV_EXAMPLE_PATH = path.join(ROOT, ".env.example");
const OUT_PATH = path.join(ROOT, "js", "config.js");

function parseEnv(content) {
  const out = {};
  content.split(/\r?\n/).forEach((rawLine) => {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) return;
    const eq = line.indexOf("=");
    if (eq === -1) return;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  });
  return out;
}

let sourcePath = ENV_PATH;
if (!fs.existsSync(ENV_PATH)) {
  console.warn(
    "[vyrona] No .env found — using .env.example placeholders. " +
      "Supabase sync will stay disabled until you add a real .env and rerun this script."
  );
  sourcePath = ENV_EXAMPLE_PATH;
}

const env = parseEnv(fs.readFileSync(sourcePath, "utf8"));

const url = env.VITE_SUPABASE_URL || "";
const anonKey = env.VITE_SUPABASE_ANON_KEY || "";
const appName = env.VITE_APP_NAME || "Vyrona";

const isPlaceholder =
  !url || url.includes("YOUR-PROJECT-REF") || !anonKey || anonKey.includes("your-anon-public-key");

const banner = `// AUTO-GENERATED by build-config.js — do not edit by hand.
// Regenerate with: node build-config.js
// This file is safe to ship (anon key is a public, RLS-protected key),
// but keep your real ".env" out of source control.
`;

const body = `export const CONFIG = Object.freeze({
  APP_NAME: ${JSON.stringify(appName)},
  SUPABASE_URL: ${JSON.stringify(url)},
  SUPABASE_ANON_KEY: ${JSON.stringify(anonKey)},
  SUPABASE_CONFIGURED: ${!isPlaceholder},
});
`;

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, banner + body);

console.log(
  `[vyrona] Wrote ${path.relative(ROOT, OUT_PATH)} — Supabase ${
    isPlaceholder ? "NOT configured (guest/offline mode only)" : "configured ✔"
  }`
);
