#!/usr/bin/env node
/**
 * Vyrona config builder.
 *
 * Resolves Supabase credentials in this order:
 *   1. process.env (set via Netlify dashboard env vars, or any CI)
 *   2. a local ".env" file (for local dev)
 *   3. ".env.example" placeholders (so the app still boots in guest mode)
 *
 * Writes "js/config.js" — a small ES module the rest of the app imports.
 * This keeps Supabase credentials out of index.html / the login screen
 * and out of source control (.env is git-ignored).
 *
 * Usage:
 *   node build-config.js
 *
 * No dependencies required — plain Node.js only.
 */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const ENV_PATH = path.join(ROOT, ".env");
const ENV_EXAMPLE_PATH = path.join(ROOT, ".env.example");
const OUT_PATH = path.join(ROOT, "js", "config.js");

function parseEnv(content) {
  const out = {};
  content.split(/\r?\n/).forEach((rawLine) => {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) return;
    const eq = line.indexOf("=");
    if (eq === -1) return;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  });
  return out;
}

// 1. Prefer real CI/host environment variables (Netlify, Vercel, etc).
let url = process.env.VITE_SUPABASE_URL || "";
let anonKey = process.env.VITE_SUPABASE_ANON_KEY || "";
let appName = process.env.VITE_APP_NAME || "";
let source = "process.env (Netlify/CI env vars)";

// 2. Fall back to a local ".env" file for local dev.
if (!url || !anonKey) {
  let sourcePath = null;
  if (fs.existsSync(ENV_PATH)) {
    sourcePath = ENV_PATH;
    source = ".env";
  } else if (fs.existsSync(ENV_EXAMPLE_PATH)) {
    sourcePath = ENV_EXAMPLE_PATH;
    source = ".env.example (placeholders — guest/offline mode only)";
    console.warn(
      "[vyrona] No .env and no host env vars found — using .env.example placeholders. " +
        "Supabase sync will stay disabled until you add real credentials."
    );
  }

  if (sourcePath) {
    const fileEnv = parseEnv(fs.readFileSync(sourcePath, "utf8"));
    url = url || fileEnv.VITE_SUPABASE_URL || "";
    anonKey = anonKey || fileEnv.VITE_SUPABASE_ANON_KEY || "";
    appName = appName || fileEnv.VITE_APP_NAME || "";
  } else {
    console.warn(
      "[vyrona] No .env, no .env.example, and no host env vars found — " +
        "shipping with empty credentials (guest/offline mode only)."
    );
  }
}

appName = appName || "Vyrona";

const isPlaceholder =
  !url || url.includes("YOUR-PROJECT-REF") || !anonKey || anonKey.includes("your-anon-public-key");

const banner = `// AUTO-GENERATED by build-config.js — do not edit by hand.
// Regenerate with: node build-config.js
// This file is safe to ship (anon key is a public, RLS-protected key),
// but keep your real ".env" out of source control.
`;

const body = `export const CONFIG = Object.freeze({
  APP_NAME: ${JSON.stringify(appName)},
  SUPABASE_URL: ${JSON.stringify(url)},
  SUPABASE_ANON_KEY: ${JSON.stringify(anonKey)},
  SUPABASE_CONFIGURED: ${!isPlaceholder},
});
`;

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, banner + body);

console.log(
  `[vyrona] Wrote ${path.relative(ROOT, OUT_PATH)} (source: ${source}) — Supabase ${
    isPlaceholder ? "NOT configured (guest/offline mode only)" : "configured ✔"
  }`
);
